// `use suppressHydrationWarning`
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";
import Banners from "@/Components/Banners/Banners";
import Image from "next/image";
import Button from "@/Components/Button/Buttons";
import Icons from "@/Components/Icons/Icons";
import BannerSkilled from "@/Components/Banners/BannerSkilled";
import Testimonials from "@/Components/Testimonials/Testimonials";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Hash Software",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en" className="hydrated"  data-lt-installed="true" 
     data-suppress-hydration-warning="true">
      <body  data-new-gr-c-s-check-loaded="14.1211.0" data-gr-ext-installed="true">
        <Header />

        

        <BannerSkilled />

        <div className="flex items-center bg-pinkbg py-32">
            <div className="flex flex-col relative ">
                <Image src="/images/pink-shape-1.png" className="w-full absolute left-6" alt="image" width={300} height={200} />
                <Image src="/images/pink-shape-2.png" className="w-full  left-6" alt="image" width={300} height={200} />
                <Image src="/images/pink-shape-3.png" className="w-full absolute left-6" alt="image" width={300} height={200} />
            </div>
            <div className="flex flex-col items-center gap-2 ">
              <h2 className="text-5xxl w-3/5 leading-11 text-center font-bold capitalize">We offer end-to-end technical services.</h2>
              <p className="text-2xl text-greyc">Hash Software offers a complete range of Mobile and web-based solutions</p>
              <div className="flex flex-col items-center relative mt-14">
                <Image src="/images/PSD_05-1.png" alt="device" className="w-auto relative" width={400} height={400} />
                <div className="bg-rollingimg bg-cover after:content-[*] w-4/5 cover h-98 top-6 left-24 ml-2 mt-2 rounded-lg absolute w-auto animate-rollimg transform -skew-x-6 -rotate-3 skew-y-2" ></div>
              </div>
            </div>
            <div className="flex flex-col relative ">
                <Image src="/images/pink-shape-4.png" className="w-full absolute" alt="image" width={300} height={200} />
                <Image src="/images/pink-shape-5.png" className="w-full  " alt="image" width={300} height={200} />
                <Image src="/images/pink-shape-6.png" className="w-full absolute " alt="image" width={300} height={200} />
            </div>
        </div>

        <div className="flex flex-wrap px-24 py-24">
          <div className="flex w-full justify-center flex-wrap items-center">
              <div className="w-2/5">
                <h2 className="text-5xxl leading-11 font-bold capitalize">We offer end-to-end technical services.</h2>
                <p className="text-2xl text-greyc">Hash Software offers a complete range of Mobile and web-based solutions</p>
              </div>
              <div className="w-3/12">
                <div className="flex flex-col bg-bluebox gap-3 min-h-custom1 p-10">
                  <Image src="/images/graphic-01-01.svg" className="w-1/3 cover" width={50} height={50} />
                  <h3 className="text-2xl font-bold">Graphic Design</h3>
                  <p className="text-greyc text-lg leading-9 font-semibold">We make designs that capture everyone’s attention. With creativity as the main ingredient, our designs will captivate the audience and improve your brand identity..</p>
                </div>
              </div>
              <div className="w-3/12">
                <div className="flex flex-col gap-3 min-h-custom1 p-10">
                  <Image src="/images/web_dev-01.svg" className="w-1/3 cover" width={50} height={50} />
                  <h3 className="text-2xl font-bold">Back-End Development </h3>
                  <p className="text-greyc text-lg leading-9 font-semibold">Backend development is the backbone of your website. Our team knows how to give a promising structure to your website that even your critics will appreciate</p>
                </div>
              </div>
              <div className="w-2/5">
                <div className="flex w-full justify-between items-center">
                  <button className="bg-mainbtn p-6 rounded-full text-white shadow-inner"><Icons name="right" className="font-bold"/></button>
                  
                  <div className="flex flex-col w-3/5 gap-3 min-h-custom1 bg-bluebox p-10">
                    <Image src="/images/web_design-01.svg" className="w-1/3 cover" width={50} height={50} />
                    <h3 className="text-2xl font-bold">Front-End Development                    </h3>
                    <p className="text-greyc text-lg leading-9 font-semibold">Frontend development plays a pivotal role in a website’s performance. To make sure your website is user friendly; our team uses advanced tools that reflect the true essence of your brand to your visitors</p>
                  </div>
                </div>
              </div>
              <div className="w-3/12">
                <div className="flex flex-col gap-3 min-h-custom1 p-10">
                  <Image src="/images/mobile_app-01.svg" className="w-1/3 cover" width={50} height={50} />
                  <h3 className="text-2xl font-bold">Mobile App Development                  </h3>
                  <p className="text-greyc text-lg leading-9 font-semibold">Smartphone users have gradually increased in number. We specialize in making mobile apps that establish a trustworthy connection with the customers and help them access your services faster.</p>
                </div>
              </div>
              <div className="w-3/12">
                <div className="flex flex-col bg-bluebox gap-3 min-h-custom1 h-full p-10">
                  <Image src="/images/seo-01-01-01.svg" className="w-1/3 cover" width={50} height={50} />
                  <h3 className="text-2xl font-bold">SEO / Digital Marketing
                  </h3>
                  <p className="text-greyc text-lg leading-9 font-semibold">Our team has helped hundreds of brands in establishing themselves online. From creating engaging content and online ads to social media strategy, we know the A to Z of digital marketing.</p>
                </div>
              </div>
          </div>
        </div>
        <div className="bg-navybg py-32">
            <div className="flex flex-wrap px-24">
              <div className="w-1/2 items-center">
                <h2 className="text-5xxl font-bold text-white">Get Full Branding</h2>
                <p className="text-xl text-white leading-10 opacity-60 pr-8">Hash Software is the epitome of experience and creativity. We are a team of highly-experienced individuals working tirelessly to meet the needs of our clients. Over the years, with ingenuity, we have helped brands re-discover their potential.
Started as a small company, we are now a proud brand offering services to clients hailing from over 20 different countries scattered around the world.
Our technology-oriented mindset and incessant love for innovation have brought us this far. Our uniqueness lies not just in giving the best of our services but also in understanding a brand to its core.
At affordable prices, we offer full branding services that will help your brand evolve beyond expectations. Join the prestigious list of clients that have counted on us for years and have given us 5 stars.</p>
                  <Button 
                  className="bg-mainbtn py-3 w-40 mt-6 text-white font-bold shadow-inner">
                    Get a Quote
                    </Button>      
              </div>
              <div className="w-1/2">
                <div className="right-brand relative">
                  <Image src="/images/branding-1.png" className="cover relative z-50 w-full items-center" width={200} height={200} />
                  <div className="brand-bg absolute z-20 border-2 border-primary rounded-full animate-growimg-delay"></div>
                  <div className="brand-bg absolute z-20 border-2 border-primary rounded-full animate-growimg-delay2"></div>
                  <div className="brand-bg absolute z-20 border-2 border-primary rounded-full animate-growimg-delay3"></div>
                  <div className="brand-bg absolute z-20 border-2 border-primary rounded-full animate-growimg-delay4"></div>
                  <div className="brand-bg absolute z-20 border-2 border-primary rounded-full animate-growimg-delay5"></div>
                  <div className="brand-bg absolute z-20 border-2 border-primary rounded-full animate-growimg-delay6"></div>
                  <div className="brand-bg absolute z-20 border-2 border-primary rounded-full animate-growimg-delay7"></div>
                  <div className="brand-bg absolute z-20 border-2 border-primary rounded-full animate-growimg-delay8"></div>
                  <div className="brand-bg absolute z-20 border-2 border-primary rounded-full animate-growimg-delay9"></div>
                </div>
              </div>
            </div>
        </div>

        <div className="flex flex-wrap py-32">
          <div className="w-1/3">
            <div className="green-gallery relative">
              <Image src="/images/green-shape-1.png" className="w-auto absolute top-0" width={300} height={100} />
              <Image src="/images/green-shape-2.png" className="w-auto absolute " width={380} height={200} />
              <Image src="/images/green-shape-3.png" className="w-auto absolute " width={300} height={100} />
              <Image src="/images/green-shape-4.png" className="w-auto absolute " width={300} height={100} />
              <Image src="/images/green-shape-5.png" className="w-auto absolute " width={300} height={100} />
            </div>
          </div>
          <div className="w-2/3">
            <div className="flex flex-col gap-4 pr-36">
              <h2 className="text-5xxl font-bold">Proven Excellence In Development Services:</h2>
              <p className="text-lg text-greyc leading-10">Hash Software is equipped with all the knowledge it takes to give wings to your brand. Till now, we have given valuable services to over 200+ companies all around the world. With consistent efforts of web developers, designers, and marketers, our team offers 360-degree development to your brand. We have successfully established our name is assisting all kinds of brands coming from different domains. Eight years went by, and we nailed over 1000+ projects. Even today, when our team works on a new project, we always take it as the very first.

No matter where you are from, where your target audience is, what your goals are, or the industry you come from; if you are looking for excellence and quality at affordable prices, you have come to the right place.

Our team believes in taking full advantage of the digital age we are living in. It is full of opportunities, infinite potential, and unfathomable scope. With the right web development, our adamant team can take you way ahead of your competitors. This way your brand can flourish like never before.
Give us a try once, and see it for yourself.</p>
            </div>
            
          </div>
        </div>

        <div className="flex flex-col justify-center bg-greyl pt-10 px-24 mb-80 gap-6">
            {/* <img src="/images/img-s-10.png" className="absolute top-0 left-0 opacity-30" width={400} height={100} /> */}
            
            <div className="relative w-full flex flex-col my-10 mx-auto items-center">
                <h4 className="text-base text-navybg mb-6 capitalize">Key Features</h4>
                <h3 className="text-6xl font-semibold capitalize text-navybg">Services we
                provide</h3>
                <img src="/images/project-shape-1.png" className="w-auto absolute top-0 left-32" alt="hash" width={100} height={100}/>
                <img src="/images/project-shape-2.png" className="w-auto absolute top-0 right-32" alt="hash" width={100} height={100}/>
            </div>
            
            <div className="flex md:flex-nowrap flex-wrap gap-4 items-center mt-10 -mb-52 relative z-50">
              <div className="flex flex-col gap-4 bg-navybg p-10 h-99 w-1/4 rounded-3xl">
                <img src="/images/icon-s-5.png" className="" width={100} height={100} />
                <h4 className="text-white text-3xl font-bold">Development</h4>
                <p className="text-white text-md">Development and building amazing digital products with best user experiences strategy.</p>
                <button className="text-white hover:text-primary flex gap-2 bg-transparent ">Learn More <Icons name="right" /> </button>
              </div>
              <div className="flex flex-col gap-4 bg-navybg p-10 h-99 w-1/4 rounded-3xl">
                <img src="/images/icon-s-6.png" className="" width={100} height={100} />
                <h4 className="text-white text-3xl font-bold">Marketing</h4>
                <p className="text-white text-md">Marketing services starts and ends within a strategy builds wireframe & solid prototyping</p>
                <button className="text-white hover:text-primary flex gap-2 bg-transparent ">Learn More <Icons name="right" /> </button>
              </div>
              <div className="flex flex-col gap-4 bg-navybg p-10 h-99 w-1/4 rounded-3xl">
                <img src="/images/icon-s-7.png" className="" width={100} height={100} />
                <h4 className="text-white text-3xl font-bold">Design</h4>
                <p className="text-white text-md">We design professional looking yet simple Logo are search engine and user friendly.</p>
                <button className="text-white hover:text-primary flex gap-2 bg-transparent ">Learn More <Icons name="right" /> </button>
              </div>
              <div className="flex flex-col gap-4 bg-navybg p-10 h-99 w-1/4 rounded-3xl">
                <img src="/images/icon-s-8.png" className="" width={100} height={100} />
                <h4 className="text-white text-3xl font-bold">Technology</h4>
                <p className="text-white text-md">Social media posts design Infographic design and email imagery security and updates.</p>
                <button className="text-white hover:text-primary flex gap-2 bg-transparent ">Learn More <Icons name="right" /> </button>
              </div>
            </div>
        </div>

        <div className="flex flex-col bg-servicend items-center jusify-center pt-32 pb-80 px-24 mb-10">
          <div className="flex justify-between items-center mb-24 w-3/5">
            <img src="/images/fanfact-1.jpg" className="w-auto transform -rotate-6" width={100} height={100} />
            <h2 className="text-7xl leading-11 text-center capitalize"> <span className="font-semibold"> company </span> <br/> inside</h2>
            <img src="/images/fanfact-2.jpg" className="w-auto transform rotate-6" width={100} height={100} />
          </div>
          <div className="flex justify-between relative items-center w-1/2 mt-24 ">
            <div className="relative z-50">
              <p className="text-xl mb-4">Team Members</p>
              <h3 className="text-6xl text-black uppercase font-bold">22+</h3>
            </div>
            <div className="relative z-50">
              <p className="text-xl mb-4">Team Members</p>
              <h3 className="text-6xl text-black uppercase font-bold">22+</h3>
            </div>
            <div className="relative z-50">
              <p className="text-xl mb-4">Team Members</p>
              <h3 className="text-6xl text-black uppercase font-bold">22+</h3>
            </div>
            <img src="/images/bg-counter.svg" className="w-auto absolute -top-80 z-0" width={100} height={100} />
          </div>
        </div>

        <Testimonials/>

        <div className="flex flex-col text-center items-center justify-center py-32 px-24 gap-6">
            <div className="relative">
              <h4 className="text-base text-primary capitalize">Achievement</h4>
              <div className="absolute top-2 -left-20 w-14 h-1 bg-primary"></div>
            </div>
            <h2 className="text-7xl w-3/5 font-bold capitalize">Amazing interactive design
                and user experience for better
                productivity.</h2>
              <div className="flex flex-col relative items-center gap-8 w-1/4">
                <Image src="/images/img-s-13.webp" className="" width={100} height={100} />
                <p className="text-base text-greyc font-semobold">Use customer data to build great and solid product experiences that convert.</p>
                <button className="text-lg font-semibold bg-primary text-white px-6 py-4 rounded-full hover:bg-white hover:text-primary border-2 border-primary">Let's Get connected</button>
                <img src="/images/img-s-14.webp" className="w-auto absolute top-0 -left-80" width={80} height={100} />
                <img src="/images/img-s-15.webp" className="w-auto absolute top-0 -right-96" width={80} height={100} />
              </div>
              <div className="">
                <img src="/images/img-s-9-dark4.png" className="w-4/5 mx-auto"/>
              </div>
        </div>

       

        <Footer/>
      </body>
    </html>
  );
}
