// `use suppressHydrationWarning`
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en" className="hydrated"  data-lt-installed="true" 
     data-suppress-hydration-warning="true">
      <body  data-new-gr-c-s-check-loaded="14.1211.0" data-gr-ext-installed="true">
        <h1>Home Page</h1>
        {children}
        
      </body>
    </html>
  );
}
