// `use suppressHydrationWarning`
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";
import HeaderNew from "@/Components/Header/HeaderNew";
import FooterNew from "@/Components/Footer/FooterNew";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Hash Software",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en" className="hydrated"  data-lt-installed="true" 
     data-suppress-hydration-warning="true">
      <body  data-new-gr-c-s-check-loaded="14.1211.0" data-gr-ext-installed="true">
        
        <HeaderNew/>
      
        {children}
      
        <FooterNew/>
      
      </body>
    </html>
  );
}
